# Generated by Django 2.2.5 on 2020-01-21 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('passout_year', models.IntegerField(default=1990)),
                ('registration_number', models.CharField(default='', max_length=15)),
                ('phone', models.CharField(default='', max_length=15)),
                ('lat', models.DecimalField(blank=True, decimal_places=20, default='', max_digits=20, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=20, default='', max_digits=20, null=True)),
                ('skills1', models.CharField(default='', max_length=100)),
                ('skills2', models.CharField(default='', max_length=100)),
                ('skills3', models.CharField(default='', max_length=100)),
                ('proffesion', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
