# Generated by Django 3.0 on 2020-01-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('longi', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
            ],
        ),
    ]
