# Generated by Django 2.2.5 on 2020-01-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(editable=False, max_length=50, unique=True)),
                ('email', models.EmailField(editable=False, max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=100)),
            ],
        ),
    ]
