# Generated by Django 2.2.5 on 2020-01-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
