# Generated by Django 3.0.2 on 2020-01-21 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20200121_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('college_name', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.AdminModel')),
            ],
        ),
    ]
