# Generated by Django 2.2.5 on 2020-01-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20200121_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_userinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='admin_userinfo',
            name='passout_year',
            field=models.IntegerField(default=1990),
        ),
    ]
