# Generated by Django 3.0.2 on 2020-01-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(default='', max_length=50)),
                ('about', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
